services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      # 경로가 달라지면 마운트 안됨 -> 이 경우, 권한이 맞지 않으면 마운트가 안되는 문제
      - ../../db/mongodb/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
